// Data for the 3CC Framework Visualization
const data = [
  {
    stakeholder: "Enterprises",
    levels: [
      {
        level: "Cognitive Companions",
        similarWork: [
          {
            name: "Microsoft Cortana",
            link: "https://www.microsoft.com/en-us/cortana",
            benefits: "Increased employee productivity; personalized tools.",
            challenges: "Employee adoption resistance; integration with existing systems.",
            technologies: "Natural Language Processing, Machine Learning",
            ethicalConsiderations: "Employee data privacy; transparency in AI decision-making.",
            implementationStatus: "Widely adopted",
            impact: "Reduction in operational costs; improved employee satisfaction.",
          },
          {
            name: "IBM Watson Assistant",
            link: "https://www.ibm.com/cloud/watson-assistant/",
            benefits: "Improved customer service; efficient query resolution.",
            challenges: "Customization complexity; initial setup costs.",
            technologies: "AI Chatbots, NLP",
            ethicalConsiderations: "Data handling policies; user consent.",
            implementationStatus: "Widely adopted",
            impact: "Enhanced customer engagement; faster response times.",
          },
          {
            name: "Salesforce Einstein",
            link: "https://www.salesforce.com/products/einstein/overview/",
            benefits: "Predictive analytics; personalized customer experiences.",
            challenges: "Data integration; requires quality data.",
            technologies: "Machine Learning, Predictive Analytics",
            ethicalConsiderations: "Customer data privacy; algorithmic transparency.",
            implementationStatus: "Widely adopted",
            impact: "Increased sales efficiency; better customer insights.",
          },
        ],
      },
      {
        level: "Cognitive Colleagues",
        similarWork: [
          {
            name: "Slack with AI integrations",
            link: "https://slack.com/apps",
            benefits: "Enhanced team collaboration; automated workflows.",
            challenges: "Over-reliance on automation; data security.",
            technologies: "AI Bots, Integration APIs",
            ethicalConsiderations: "Data sharing consent; security protocols.",
            implementationStatus: "Growing adoption",
            impact: "Improved communication; streamlined processes.",
          },
          {
            name: "Microsoft Teams AI Features",
            link: "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software",
            benefits: "Transcription and translation; meeting productivity.",
            challenges: "Language accuracy; requires stable internet.",
            technologies: "Speech Recognition, Machine Translation",
            ethicalConsiderations: "Data privacy during calls; consent for recording.",
            implementationStatus: "Growing adoption",
            impact: "Efficient meetings; better accessibility.",
          },
          {
            name: "Cisco Webex Assistant",
            link: "https://www.webex.ai/",
            benefits: "AI meeting assistant; captures action items.",
            challenges: "Integration with calendars; accuracy of notes.",
            technologies: "Speech-to-Text, AI Assistants",
            ethicalConsiderations: "Recording consent; data security.",
            implementationStatus: "Growing adoption",
            impact: "Improved meeting outcomes; accountability.",
          },
        ],
      },
      {
        level: "Cognitive Collectives",
        similarWork: [
          {
            name: "IBM Watson Discovery",
            link: "https://www.ibm.com/cloud/watson-discovery",
            benefits: "Enterprise data analysis; uncover hidden insights.",
            challenges: "Data silos; requires data scientists.",
            technologies: "AI-powered Data Mining",
            ethicalConsiderations: "Confidentiality; data governance.",
            implementationStatus: "Emerging",
            impact: "Informed decision-making; innovation acceleration.",
          },
          {
            name: "SAP Leonardo",
            link: "https://help.sap.com/docs/SAP_Leonardo_IoT",
            benefits: "Integrates AI across business processes.",
            challenges: "Complex implementation; training required.",
            technologies: "AI, IoT, Machine Learning",
            ethicalConsiderations: "Process transparency; employee impact.",
            implementationStatus: "Emerging",
            impact: "Streamlined operations; competitive advantage.",
          },
          {
            name: "Accenture's SynOps",
            link: "https://www.accenture.com/us-en/services/business-process-services/synops-operating-engine",
            benefits: "AI-driven operations platform; enhances efficiency.",
            challenges: "Requires organizational change; cost.",
            technologies: "Automation, Analytics, AI",
            ethicalConsiderations: "Job displacement concerns; ethical AI use.",
            implementationStatus: "Emerging",
            impact: "Operational excellence; data-driven strategies.",
          },
        ],
      },
    ],
  },
  {
    stakeholder: "Educational Institutions",
    levels: [
      {
        level: "Cognitive Companions",
        similarWork: [
          {
            name: "Carnegie Mellon's SARA",
            link: "https://articulab.hcii.cs.cmu.edu/projects/sara/",
            benefits: "Personalized tutoring; improved student outcomes.",
            challenges: "Scalability; content updates.",
            technologies: "AI Tutoring Systems, Machine Learning",
            ethicalConsiderations: "Student data privacy; equity of access.",
            implementationStatus: "Growing adoption",
            impact: "Enhanced learning experiences; better retention.",
          },
          {
            name: "Duolingo",
            link: "https://www.duolingo.com/",
            benefits: "Personalized language learning; gamification.",
            challenges: "Limited to language; requires internet access.",
            technologies: "Adaptive Learning, Gamification",
            ethicalConsiderations: "Data collection; content appropriateness.",
            implementationStatus: "Widely adopted",
            impact: "Accessible language education; global reach.",
          },
          {
            name: "Knewton Alta",
            link: "https://www.wiley.com/en-us/education/alta",
            benefits: "Adaptive learning platform; personalized content.",
            challenges: "Integration with curricula; cost for institutions.",
            technologies: "Adaptive Learning Technology",
            ethicalConsiderations: "Student data security; algorithm transparency.",
            implementationStatus: "Growing adoption",
            impact: "Improved student performance; tailored instruction.",
          },
        ],
      },
      {
        level: "Cognitive Colleagues",
        similarWork: [
          {
            name: "Piazza",
            link: "https://piazza.com/",
            benefits: "Collaborative learning; peer-to-peer support.",
            challenges: "Student engagement; moderation needs.",
            technologies: "AI Moderation, Collaboration Tools",
            ethicalConsiderations: "Data privacy; appropriate content.",
            implementationStatus: "Widely adopted",
            impact: "Enhanced classroom interaction; community building.",
          },
          {
            name: "Google Classroom AI Tools",
            link: "https://edu.google.com/products/classroom/",
            benefits: "Facilitates collaboration; streamlines assignments.",
            challenges: "Dependence on Google ecosystem; varying tech access.",
            technologies: "Cloud Computing, AI Integration",
            ethicalConsiderations: "Data usage policies; student privacy.",
            implementationStatus: "Widely adopted",
            impact: "Efficient class management; increased collaboration.",
          },
          {
            name: "Edmodo",
            link: "https://edmodo.online/",
            benefits: "Social learning network; connects teachers and students.",
            challenges: "Content moderation; feature complexity.",
            technologies: "Social Networking, AI Enhancements",
            ethicalConsiderations: "Online safety; data protection.",
            implementationStatus: "Growing adoption",
            impact: "Improved communication; resource sharing.",
          },
        ],
      },
      {
        level: "Cognitive Collectives",
        similarWork: [
          {
            name: "AI for K-12 Initiative",
            link: "https://ai4k12.org/",
            benefits: "Collaborative curriculum development; AI literacy.",
            challenges: "Standardization; teacher training.",
            technologies: "Educational AI Tools",
            ethicalConsiderations: "Accessibility; unbiased content.",
            implementationStatus: "Emerging",
            impact: "Future-ready students; widespread AI understanding.",
          },
          {
            name: "Stanford's HAI",
            link: "https://hai.stanford.edu/",
            benefits: "Research on AI's societal effects; policy development.",
            challenges: "Funding; interdisciplinary collaboration.",
            technologies: "AI Research Platforms",
            ethicalConsiderations: "Societal impact; ethical AI development.",
            implementationStatus: "Emerging",
            impact: "Informed policies; societal benefits.",
          },
          {
            name: "MIT's Climate CoLab",
            link: "https://climatecolab.org/",
            benefits: "Collective problem-solving; climate action.",
            challenges: "Participant engagement; solution implementation.",
            technologies: "Crowdsourcing, Collective Intelligence",
            ethicalConsiderations: "Inclusivity; fair use of contributions.",
            implementationStatus: "Growing adoption",
            impact: "Innovative solutions; global collaboration.",
          },
        ],
      },
    ],
  },
  {
    stakeholder: "Developers",
    levels: [
      {
        level: "Cognitive Companions",
        similarWork: [
          {
            name: "GitHub Copilot",
            link: "https://copilot.github.com/",
            benefits: "AI code assistant; increases coding efficiency.",
            challenges: "Potential for code bias; reliance on AI.",
            technologies: "AI Code Completion, Machine Learning",
            ethicalConsiderations: "Licensing issues; code originality.",
            implementationStatus: "Widely adopted",
            impact: "Accelerated development; enhanced productivity.",
          },
          {
            name: "Visual Studio IntelliCode",
            link: "https://visualstudio.microsoft.com/services/intellicode/",
            benefits: "AI-assisted coding; context-aware suggestions.",
            challenges: "Limited to supported languages; learning curve.",
            technologies: "Machine Learning, Code Analysis",
            ethicalConsiderations: "Privacy of codebases; data usage.",
            implementationStatus: "Widely adopted",
            impact: "Improved code quality; developer support.",
          },
          {
            name: "TabNine",
            link: "https://www.tabnine.com/",
            benefits: "AI code completion; supports multiple languages.",
            challenges: "Integration with IDEs; subscription costs.",
            technologies: "Deep Learning, Natural Language Processing",
            ethicalConsiderations: "Data privacy; dependency on AI.",
            implementationStatus: "Growing adoption",
            impact: "Faster coding; reduced errors.",
          },
        ],
      },
      {
        level: "Cognitive Colleagues",
        similarWork: [
          {
            name: "GitHub",
            link: "https://github.com/",
            benefits: "Collaborative coding platform; version control.",
            challenges: "Learning curve; managing contributions.",
            technologies: "Git, Collaboration Tools",
            ethicalConsiderations: "Open-source licensing; code ownership.",
            implementationStatus: "Widely adopted",
            impact: "Community building; collective development.",
          },
          {
            name: "Stack Overflow with OverflowAI",
            link: "https://stackoverflow.blog/2023/07/27/announcing-overflowai/",
            benefits: "Community support with AI assistance; faster answers.",
            challenges: "Accuracy of AI responses; moderation.",
            technologies: "AI Chatbots, Knowledge Bases",
            ethicalConsiderations: "Content accuracy; user trust.",
            implementationStatus: "Growing adoption",
            impact: "Enhanced developer support; knowledge sharing.",
          },
          {
            name: "Atlassian's Jira with AI",
            link: "https://www.atlassian.com/platform/artificial-intelligence",
            benefits: "Team collaboration tools; project management.",
            challenges: "Complexity; integration with other tools.",
            technologies: "AI Analytics, Automation",
            ethicalConsiderations: "Data security; employee monitoring.",
            implementationStatus: "Widely adopted",
            impact: "Efficient project tracking; improved collaboration.",
          },
        ],
      },
      {
        level: "Cognitive Collectives",
        similarWork: [
          {
            name: "TensorFlow",
            link: "https://www.tensorflow.org/",
            benefits: "Open-source AI framework; collaborative development.",
            challenges: "Steep learning curve; performance optimization.",
            technologies: "Machine Learning, Deep Learning",
            ethicalConsiderations: "Responsible AI use; inclusivity.",
            implementationStatus: "Widely adopted",
            impact: "Accelerated AI research; community contributions.",
          },
          {
            name: "PyTorch",
            link: "https://pytorch.org/",
            benefits: "Dynamic computation; community-driven improvements.",
            challenges: "Compatibility issues; documentation depth.",
            technologies: "Deep Learning Framework",
            ethicalConsiderations: "Open-source governance; equitable access.",
            implementationStatus: "Widely adopted",
            impact: "Innovative AI solutions; collaborative progress.",
          },
          {
            name: "LF AI & Data Foundation",
            link: "https://lfaidata.foundation/",
            benefits: "Collaborative AI projects; industry standards.",
            challenges: "Coordination among projects; resource allocation.",
            technologies: "Open-source AI Platforms",
            ethicalConsiderations: "Transparency; fair contribution recognition.",
            implementationStatus: "Emerging",
            impact: "Unified AI efforts; industry advancements.",
          },
        ],
      },
    ],
  },
  {
    stakeholder: "Government",
    levels: [
      {
        level: "Cognitive Companions",
        similarWork: [
          {
            name: 'Singapore\'s "Ask Jamie"',
            link: "https://www.tech.gov.sg/products-and-services/for-government-agencies/productivity-and-marketing/vica/",
            benefits: "Virtual assistant for citizens; accessible information.",
            challenges: "Language nuances; updating content.",
            technologies: "Chatbots, Natural Language Processing",
            ethicalConsiderations: "Citizen data privacy; service accessibility.",
            implementationStatus: "Widely adopted",
            impact: "Improved citizen engagement; efficient service delivery.",
          },
          {
            name: "IRS Interactive Tax Assistant",
            link: "https://www.irs.gov/help/ita",
            benefits: "Taxpayer assistance; quick answers.",
            challenges: "Complex tax queries; user interface.",
            technologies: "AI Chatbots, Knowledge Bases",
            ethicalConsiderations: "Accuracy of information; data protection.",
            implementationStatus: "Growing adoption",
            impact: "Reduced wait times; better taxpayer support.",
          },
          {
            name: "India's MyGov Corona Helpdesk",
            link: "https://www.mygov.in/covid-19/",
            benefits: "COVID-19 information; 24/7 availability.",
            challenges: "Information overload; misinformation management.",
            technologies: "AI Chatbots, Messaging Platforms",
            ethicalConsiderations: "Health data privacy; accurate updates.",
            implementationStatus: "Widely adopted",
            impact: "Public health awareness; crisis communication.",
          },
        ],
      },
      {
        level: "Cognitive Colleagues",
        similarWork: [
          {
            name: "Barcelona Smart City",
            link: "https://ajuntament.barcelona.cat/digital/en",
            benefits: "Collaborative urban management; improved infrastructure.",
            challenges: "Infrastructure costs; citizen engagement.",
            technologies: "IoT, AI Analytics",
            ethicalConsiderations: "Surveillance concerns; data transparency.",
            implementationStatus: "Growing adoption",
            impact: "Enhanced quality of life; sustainable development.",
          },
          {
            name: "FEMA's Use of AI",
            link: "https://www.fema.gov/",
            benefits: "Disaster management; efficient resource allocation.",
            challenges: "Data accuracy; coordination with agencies.",
            technologies: "Predictive Analytics, AI Coordination Tools",
            ethicalConsiderations: "Privacy in crisis; equitable aid distribution.",
            implementationStatus: "Emerging",
            impact: "Faster response times; lives saved.",
          },
        ],
      },
      {
        level: "Cognitive Collectives",
        similarWork: [
          {
            name: "United Nations' AI for Good",
            link: "https://aiforgood.itu.int/",
            benefits: "Global collaboration on AI solutions; sustainable development.",
            challenges: "Coordination among nations; funding.",
            technologies: "AI Platforms, Collaborative Tools",
            ethicalConsiderations: "Global equity; responsible AI deployment.",
            implementationStatus: "Emerging",
            impact: "Progress on global challenges; international cooperation.",
          },
          {
            name: "European AI Alliance",
            link: "https://digital-strategy.ec.europa.eu/en/policies/european-ai-alliance",
            benefits: "Collaborative policy development; stakeholder engagement.",
            challenges: "Diverse interests; policy harmonization.",
            technologies: "Policy Platforms, AI Consultation Tools",
            ethicalConsiderations: "Transparency; inclusivity.",
            implementationStatus: "Emerging",
            impact: "Unified AI regulations; ethical AI advancement.",
          },
          {
            name: "OECD AI Policy Observatory",
            link: "https://oecd.ai/",
            benefits: "International cooperation on AI policies; shared insights.",
            challenges: "Data standardization; policy enforcement.",
            technologies: "Data Analysis Tools, Policy Databases",
            ethicalConsiderations: "Cultural sensitivity; policy fairness.",
            implementationStatus: "Growing adoption",
            impact: "Informed policymaking; global standards.",
          },
        ],
      },
    ],
  },
];

