name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Add your build steps here
      # Example for a static site without a build process
      - name: Build Site
        run: |
          echo "No build steps required. Site is ready to deploy."

      # Example for a site that requires building (e.g., using a static site generator)
      # Uncomment and modify the following lines if you have a build process
      # - name: Install Dependencies
      #   run: |
      #     npm install
      #
      # - name: Build Project
      #   run: |
      #     npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Change to your build output directory

